.TH BASH 1 "May 24, 2003" bash "Debian Free Documentation"
.SH NAME
bash-minimal \- A bash version configured with minimal features
.SH SYNOPSIS
bash [\fB\s-1options\s0\fR] ... [\fI\s-1file\s0\fR]

.SH DESCRIPTION

\fBbash-minimal\fR is configured using --enable-minimal-config, which
produces a shell with minimal features, close to the historical Bourne
shell. This means:
.IP "\(bu" 4
No alias expansion and the `alias' and `unalias' builtins.
.IP "\(bu" 4
No support for the alternate form of the `for' command that
behaves like the C language `for' statement.
.IP "\(bu" 4
No support for one-dimensional array shell variables.
.IP "\(bu" 4
No support for `csh'-like history substitution.
.IP "\(bu" 4
No `csh'-like brace expansion ( `b{a,b}c' ==> `bac bbc' ).
.IP "\(bu" 4
No support for recognizing `time' as a reserved word and for
displaying timing statistics for the pipeline following `time'.  This
allows pipelines as well as shell builtins and functions to be timed.
.IP "\(bu" 4
No support for the `[[' conditional command.
.IP "\(bu" 4
No support for a `csh'-like directory stack and the `pushd',
`popd', and `dirs' builtins
.IP "\(bu" 4
No support for the `((...))' command.
.IP "\(bu" 4
No support for the extended pattern matching features.
.IP "\(bu" 4
No `help' builtin, which displays help on shell builtins and
variables.
.IP "\(bu" 4
No command history and the `fc' and `history' builtin commands.
.IP "\(bu" 4
No job control features.
.IP "\(bu" 4
No special handling of filenames of the form `/dev/tcp/HOST/PORT' and
`/dev/udp/HOST/PORT' when used in redirections.
.IP "\(bu" 4
No process substitution.
.IP "\(bu" 4
No interpretation of a number of backslash-escaped characters in the
`$PS1', `$PS2', `$PS3', and `$PS4' prompt strings.
.IP "\(bu" 4
No programmable completion facilities.
.IP "\(bu" 4
No support for command-line editing and history with the Bash version
of the Readline library.
.IP "\(bu" 4
No support for a "restricted shell".  If this is enabled, Bash, when
called as `rbash', enters a restricted mode.
.IP "\(bu" 4
No `select' builtin, which allows the generation of simple menus.
.SH "SEE ALSO"
.BR bash(1)
